# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Proj1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Proj1
	pod 'SDWebImage'

  target 'Proj1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Proj1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
